### ISSUE TITLE
error with guzzlehttp/guzzle

### ISSUE THREAD

**Issue by Ekaterina20** [maksa988/laravel-unitpay#11]
Hi,

I have an error for Laravel 8 in composer
 Problem 1
    - Installation request for maksa988/laravel-unitpay 2.* -> satisfiable by maksa988/laravel-unitpay[2.x-dev, v2.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].

**Comment by maksa988** [comment]
Fixed
